### PR TITLE
Relocate ActionBarSherlock library -> actionbarsherlock-library

### PR DESCRIPTION
**Pull request by rgladwell**
The Maven relocation feature allows us to move the ActionBarSherlock artifactId to a more meaningful string without breaking people's builds:

http://maven.apache.org/guides/mini/guide-relocation.html

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can't be auto-merged anymore. I'd prefer to do this without renaming the folder itself. I will implement for 4.2.

**Comment by rgladwell** [comment]
Fair enough, when do you think you'll be releasing 4.2?

**Comment by JakeWharton** [comment]
It's about a week away. Hopefully sooner but it all depends on my workload
this coming week.

**Comment by rgladwell** [comment]
Thanks for the feedback.

**Pull request closed without merging**
