### PR TITLE
Fix travis config

### PR DESCRIPTION
**Pull request by hameno**
This should fix the travis builds...I got a similar config working in my projects (e.g. https://github.com/PSDev/LicensesDialog)

### CODE REVIEW

**Comment by JakeWharton** [comment]
_/me sips drink waiting for Travis_

**Comment by hameno** [comment]
:D

**Comment by hameno** [comment]
Ahh I should probably change the install command so that it isn't "quiet"...

**Comment by hameno** [comment]
Well, seems to be working...

**Comment by hameno** [comment]
I think that is all I can do for now - not sure why the tests are failing, seems to be a problem with the dependencies and scope maybe?

**Comment by JakeWharton** [comment]
I'm just going to wait out Travis' incompetence rather than hack up some crazy solution. Thanks for trying, though.

**Pull request closed without merging**
