### PR TITLE
This would be very useful 

### PR DESCRIPTION
**Pull request by iNoles**
It can help to reduce duplicate coding when you have multiple Activities.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Abstracting the action bar logic into its own class is something that I do want to move towards but with the 4.x version of ActionBarSherlock.

Some of the choices that you have made, however, I take a bit of issue with. The exposing of internal functionality such as the fragment manager and internal handler as public will inevitably lead to problems with users accessing them. This was the reason for the public internal callbacks method which had package-scoped methods.

I'll leave this open as it has some things which I do want to move toward.

**Comment by iNoles** [comment]
Oh okay, looks like I need to find another way of doing it. 

getLoaderManager and ensureSupportActionBarAttached() right?

**Comment by JakeWharton** [comment]
All of the methods that were in the internal callbacks shouldn't be public since they expose the behind-the-scenes implementations of certain fragile things.

**Comment by iNoles** [comment]
Okay, I put back old internal callback method.

**Comment by JakeWharton** [comment]
I'm closing this, if you look that the `4.0-wip` progress I am already using a centralized class for management.

**Pull request closed without merging**
