### PR TITLE
Add required application element.

### PR DESCRIPTION
**Pull request by iamstuffed**
http://developer.android.com/guide/topics/manifest/manifest-element.html

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is this really required for library projects?

**Comment by iamstuffed** [comment]
I don't really know if it's absolutely necessary, but according to the documentation linked, it's required. I had issues with the new Gradle based build system validating the AndroidManifest.xml file and failing because it couldn't find the application element. 

Other libraries have an empty application tag.

**Comment by SimonVT** [comment]
Hardly any libraries have an application tag, not even google's own (e.g. support-v7). Sounds more like an issue that should be reported to the tools team.
Either way, pull requests go on the dev branch.

**Comment by iNoles** [comment]
the application tag is required for < activity >

**Pull request closed without merging**
