### PR TITLE
Fix setting dropDownSelector and dropDownHorizontalOffset to IcsSpinner from custom style

### PR DESCRIPTION
**Pull request by Alexious-sh**
All in one commit.

### CODE REVIEW

**Comment by SimonVT** [comment]
Remove the spaces, amend last commit and force push to this branch. It will update the pull request.

**Comment by Alexious-sh** [comment]
Thanks for help!

**Comment by SimonVT** [comment]
You seem to have reformatted the entire file :F

**Comment by Alexious-sh** [comment]
Oh, it's windows CR/LF :(

**Comment by SimonVT** [comment]
It'd be great if you could fix that and squash it into a single commit

**Pull request closed without merging**
