### PR TITLE
Bump up roboguice-sherlock version. Try to fix the `can't resolve startActivity()` error.

### PR DESCRIPTION
**Pull request by zhen9ao**
Intellij IDEA would complain without the jar dependency.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Does `mvn clean verify` pass?

**Comment by zhen9ao** [comment]
Yeah, it passed.

> [INFO] Reactor Summary:
> [INFO] 
> [INFO] ActionBarSherlock (Parent) ........................ SUCCESS [0.432s]
> [INFO] ActionBarSherlock ................................. SUCCESS [29.533s]
> [INFO] Sample (Parent) ................................... SUCCESS [0.005s]
> [INFO] Sample: Demos ..................................... SUCCESS [20.754s]
> [INFO] Sample: Fragments ................................. SUCCESS [18.563s]
> [INFO] Sample: RoboGuice ................................. SUCCESS [18.634s]
> [INFO] Sample: Styled .................................... SUCCESS [16.496s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1:45.547s
> [INFO] Finished at: Tue May 08 11:04:00 GMT+08:00 2012
> [INFO] Final Memory: 24M/81M
> [INFO] ------------------------------------------------------------------------

**Comment by JakeWharton** [comment]
Use `${project.version}` for the ABS depenedency.

**Comment by zhen9ao** [comment]
Done

**Comment by zhen9ao** [comment]
After changing the explicit version to `${project.version}`, the IDE still complain.

I found that Intellij doesn't import the right jar dependency but rather there are two apklib dependencies of `Library`, one `Compile` the other `Provided`.

**Comment by zhen9ao** [comment]
Roboguice-sherlock requires com.actionbarsherlock.library 4.0.2 as a provided one, do we have to change the dependency version of sample-roboguice to 4.0.2?

**Comment by JakeWharton** [comment]
That's simply the version that it compiles against. Its `provided` scope allows us to always substitute the latest version when actually using the library.

**Comment by zhen9ao** [comment]
Maybe this is a bug of Intellij, similar to this http://youtrack.jetbrains.com/issue/IDEA-81856

**Comment by JakeWharton** [comment]
Yeah it's probably not an issue with the actual Maven configuration as command line building works fine. I've voted for the issue and will watch its progress. I'm also seeing the same errors appear in IntelliJ so it's not just you.

**Pull request merged**
