### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ChristianKatzmann**
Removed many Java Compiler warnings like missing @override annotations and unnecessary casts

### CODE REVIEW

**Comment by zhen9ao** [comment]
Seems no need of this `cleanup`.

**Comment by JakeWharton** [comment]
What IDE and/or build system are you using where these are warnings? The `@Override` annotation is a compile-time enforcement only and has no effect on the resulting bytecode which is why I'm hesitant to include them. Plus a lot of the code you have added them to is copied directly from the Android sources and would create additional merge conflicts moving forward with future versions of the platform.

**Comment by ChristianKatzmann** [comment]
I'm using Eclipse and missing `@Override` annotations are marked as warnings (at least in my compiler configuration).

I just was confused that some `@Override` annotations were available and some were missing in the ABS codebase, so I pulled this changes.

**Comment by iNoles** [comment]
I think you have 1.5. You could set 1.6

**Comment by ChristianKatzmann** [comment]
That's not the point. Only difference between 1.5 and 1.6 is the fact, that overridden Interface methods should be declared too in 1.6.

**Comment by JakeWharton** [comment]
Needs rebase. Code is about to drastically change with Jelly Bean source import as well. You should consider submitting these upstream rather than to ABS.

**Pull request closed without merging**
