### PR TITLE
Fixed the suggestions in the compatibility SearchView.

### PR DESCRIPTION
**Pull request by mattkranzler5**
...ionsAdapter to use the SearchableInfo object to build the uri to query the ContentResolver with. Added missing drawables and defined the necessary attributes for the suggestions in the dropdown to work properly.

### CODE REVIEW

**Comment by DSteve595** [comment]
Yes!

**Comment by ngdinhtoan** [comment]
Could you also fix suggestion behavior when user click on search view?
Currently, when we click on search view, it will hide suggestion list view. When we click again, it don't show suggestion again.
It should always show suggestion list when user click on search view (even it's focused) like native search view.

Code:
Call onQueryRefine(mQueryTextView.getText()); on click on mQueryTextView event.

(I'm not sure it is the best way, but atleast it works for me)

**Comment by JakeWharton** [comment]
Merged to `dev`. Thanks!

**Comment by tprochazka** [comment]
Is this in 4.3.0 already?

**Comment by tprochazka** [comment]
I will reply to myself. Yer it is supported from 4.3.0 ;-)

**Pull request closed without merging**
