### PR TITLE
Update support library binaries to r11 for non-Maven users.

### PR DESCRIPTION
**Pull request by matthewmichihara**

### CODE REVIEW

**Comment by csobrinho** [comment]
although you can always fork it and place your own like I did

**Comment by agarwlGaurav** [comment]
@matthewmichihara @csobrinho  Can we safely replaced from r7 to r11? Have you guys replaced it any issues??

**Comment by matthewmichihara** [comment]
Works great for me.

**Comment by agarwlGaurav** [comment]
@matthewmichihara Thx for help.

**Comment by SimonVT** [comment]
The issue isn't that it doesn't work, the issue is that r11 isn't in maven central yet. If there is any issues with r11 they're very likely to get looked at, but updating is up to you.

**Comment by agarwlGaurav** [comment]
Thnx Simon VT.

**Comment by JakeWharton** [comment]
I'm a bit torn on whether to accept this. I'd like to hold out and persist in bugging Google more to do their job in deploying to central rather than having us do it for them...

**Comment by matthewmichihara** [comment]
Understandable. Let me know if there's any way I can help.

**Comment by JakeWharton** [comment]
Not merging, but going to push ahead on getting r12 into central.

**Comment by JakeWharton** [comment]
As in, push ahead doing it myself rather than waiting for Google.

**Comment by mauimauer** [comment]
So...any ETA when this will turn up? I'd really like to nest fragments :D

**Comment by JakeWharton** [comment]
Just replace the jar in your local copy. Or deploy a newer version of the jar to your local repo if you're using Maven.

Also,

> I'd really like to nest fragments

No. No you wouldn't. Trust me.

**Comment by william-ferguson-au** [comment]
Jake, what's happened to getting the android-support jars into Maven central?
It's become really hard to maintain builds of open-source projects because you essentially have to manually include the libs in each and every project. Using ABS and HoloEverywhere and anything that relies on the jars a real pain.

I kind of hoped Google had grown up with the move to Gradle.

**Comment by iNoles** [comment]
So far, Google is not releasing the latest version of the support library to the maven central.

**Comment by william-ferguson-au** [comment]
But there's been nothing released since v4-r7 (which was released by Jake I believe). The support library is now up to v13-r18. That's a long time between drinks.

**Comment by JakeWharton** [comment]
It's always v4. And there's no r14 through r17 so that doesn't count.

**Comment by william-ferguson-au** [comment]
OK, so perhaps there's no 14 through 17, though that's not obvious from the SDKManager.

But not sure that it's always version-4.
Latest SDKManager downloads also include:
  Android-sdk\extras\android\m2repository\com\android\support\support-v13\13.0.0
  Android-sdk\extras\android\m2repository\com\android\support\support-v13\18.0.0
as well as
  Android-sdk\extras\android\m2repository\com\android\support\support-v4\13.0.0
  Android-sdk\extras\android\m2repository\com\android\support\support-v4\18.0.0

Which suggest v4-r13, v4-r18, v13-r13 and v13-r18.

And I don't understand why the SDK Manager downloads 2 Maven repos instead of the artefacts just being deployed to a publicly visible repository.

**Comment by JakeWharton** [comment]
> But not sure that it's always version-4.

v4 is for API 4 and up. v13 is for API 13 and up. There's always been two.

> And I don't understand why the SDK Manager downloads 2 Maven repos

One for Android (AOSP) artifacts. One for proprietary Google artifacts (e.g., Google Play Services). They have different licenses.

> ...instead of the artefacts just being deployed to a publicly visible repository.

Xav says it's not licensing but I still expect that's part of it. It's also easier for them to manage.

**Comment by william-ferguson-au** [comment]
`It's also easier for them to manage.`

It's not making it any easier for us. And there's a lot more of us. :-(

I'm a huge fan of Maven, but decisions like this and the need to follow the Android design guidelines etc are causing my projects to devolve back to shipping libraries in the source. Very 1990s.

**Pull request closed without merging**
