### PR TITLE
Added localized resources

### PR DESCRIPTION
**Pull request by androidmoney**
Added localized resources for the top 10 most common languages for a total of 100 string resources.

### CODE REVIEW

**Comment by dancefire** [comment]
Why this commit is not pulled? It's very handy for apps with multiple language, otherwise {"abs__xxxx" is not translated in xx} error will be thrown during export apk. It doesn't hurt anything, so please pull.

**Comment by SimonVT** [comment]
This should either be a complete commit which includes all languages in AOSP, or people should manually include strings for languages they support. Just adding 10 is kind of half-assed.

**Comment by Prototik** [comment]
Mmm... For HoloEverywhere i develop "Translator" - grabber of strings from AOSP.
May be run once it for ABS?

**Comment by JakeWharton** [comment]
I don't want this in the core library. ABS is large enough. If people truly want this it can exist in a parallel library project.

**Comment by JakeWharton** [comment]
Please re-submit as another top-level module called `library-i18n` with all AOSP languages included. A script to parse used strings and keep this new module up-to-date given a path to an AOSP clone would also be nice.

**Pull request closed without merging**
