### PR TITLE
i18n of library as new maven project actionbarsherlock-i18n.

### PR DESCRIPTION
**Pull request by Prototik**
Manual rebuild of translates:
cd library-i18n
mvn translator:build

Auto rebuild:
Uncomment block in library-i18n/pom.xml and move it in <plugins> block;

Used HoloEverywhere Translator 1.4.2, but it not yet release. You need manual install 1.4.2 version into local repository.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Awesome! Will leave open until release since I don't want the `dev` branch to not compile.

**Comment by Prototik** [comment]
Until release of HoloEverywhere 1.4.2?

**Comment by JakeWharton** [comment]
Yeah, will it be soon? I neither use nor follow the project. I suppose I could merge since the plugin isn't actually used in compilation.

**Comment by Prototik** [comment]
Yea, soon. 3-4 days, i think. I comment this issue when it will be released.

**Comment by JakeWharton** [comment]
Excellent. Thank you! If you get a chance, can you rebase it off of the latest `dev` and rename the module to `actionbarsherlock-i18n`? If not, I'll do it myself when merging.

**Comment by Prototik** [comment]
Yea. One moment.

**Comment by Prototik** [comment]
> I don't want the dev branch to not compile.

By the way dev branch compiles, but if want to manually recompile translates without he translator 1.4.2 - fail, yea.

**Comment by Prototik** [comment]
HoloEverywhere 1.4.2 was released, Translator already available in Maven Central.

**Pull request merged**
