### PR TITLE
Update library/res/layout/sherlock_spinner_dropdown_item.xml

### PR DESCRIPTION
**Pull request by notnil**
This change made my ActionBar Drop-Down Navigation look the same as native Drop-Down Navigation.

### CODE REVIEW

**Comment by notnil** [comment]
The difference was on Android 2.3.

**Comment by SimonVT** [comment]
This attribute is already defined in the default style. I see no difference between native implementation and when running on 2.3.

**Comment by notnil** [comment]
Before Addition:



After Addition:

**Comment by SimonVT** [comment]
If you're redefining any theme attribute, make sure you extend the default styles. I've loaded up the samples in a 2.3 emulator and I'm not seeing this behavior.

**Comment by notnil** [comment]
K.  I am just using it in mine so I figured I'd see if it would be useful to others.

**Pull request closed without merging**
