### PR TITLE
Line endings

### PR DESCRIPTION
**Pull request by johnjohndoe**
I converted the `CRLF` line endings to `LF` for a bunch of .java, .xml and .html files.

@JakeWharton  I cannot tell why [Travis CI fails on the build](https://travis-ci.org/JakeWharton/ActionBarSherlock/builds/11008796). Maven and gradle run successfully here since I have not changed the code. Maybe you can re-run the Travis task.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can you re-submit this pull against the `dev` branch? Also please squash to a single commit if possible. Ignore Travis CI.

**Comment by johnjohndoe** [comment]
Done [here](https://github.com/JakeWharton/ActionBarSherlock/pull/1035). You are welcome to pick settings from my [git config](https://github.com/johnjohndoe/dotfiles/blob/master/gitconfig).

**Comment by JakeWharton** [comment]
The project is about 2.5 years old so some of the files were created back before I knew how to git properly.

**Comment by johnjohndoe** [comment]
Understandable. I had to learn this, too. No offense please. Thanks for the merge.

**Pull request closed without merging**
