### PR TITLE
Add new SeriesGuide screenshots, update to Google play links

### PR DESCRIPTION
**Pull request by UweTrottmann**
Changed the screenshots on the samples page, updated all Android Market links on that page to Google play.

### CODE REVIEW

**Comment by JakeWharton** [comment]
The website is stored in `website/resources/` in the `dev` branch and gets deployed automatically by maven (so this would be overwritten). I'd **really** appreciate if you'd make the changes there and submit a pull request against `dev` before 11:55PM PST so I can get it in the 4.0 release. I'm not sure I'll have time to do it manually before then.

**Comment by JakeWharton** [comment]
I have no idea what timezone it is where you are. You're probably asleep...

**Comment by JakeWharton** [comment]
Nevermind. I'm changing the samples page a bit until the full website rewrite.

**Comment by UweTrottmann** [comment]
Got up early, is it too late yet? I'm Central European Time (Germany). My clock says it's close to eleven on PST.

**Comment by JakeWharton** [comment]
I dropped screenshots for now from the samples page as they take far too long to get working properly and are far too manual of a process. They'll be part of an upcoming full-site rewrite with a mini-market place of ABS apps (hopefully).

**Comment by JakeWharton** [comment]
You're still front and center (and bottom...) on the index.html though!

**Comment by UweTrottmann** [comment]
Awesome :D I just saw the old screenshots and had to do something about that... The mini-market idea sounds great.
Maybe every app could also add a 'tag' in their description on 'Google Play' so you could search for ActionBarSherlock apps.

**Comment by JakeWharton** [comment]
That's not a bad idea either. I'll have to experiment.

It's too bad the Market doesn't have a proper API for fetching screenshots and leading images and the like. Would make the creation of something like that super easy.

**Pull request closed without merging**
