### PR TITLE
Theme.Sherlock.Light.DarkActionBar

### LINKED ISSUE #126: Add Theme.Sherlock.Light.DarkActionBar
...which inherits from `Theme.Holo.Light.DarkActionBar`.

### PR DESCRIPTION
**Pull request by chrisbanes**
Fixes #126

### CODE REVIEW

**Comment by chrisbanes** [comment]
Adding aac902c33e9f5311a6f70d2a22375c482294f87b back in was causing me some build problems so I've reverted it for now.

**Comment by JakeWharton** [comment]
Does this work? I get a light action bar on both pre/post 3.0 with this style.

**Comment by chrisbanes** [comment]
It's working for me, but then again I'm manually setting the Action Bar
background. I'll test it with a standard set-up.
On Dec 22, 2011 2:29 PM, "Jake Wharton" <
reply@reply.github.com>
wrote:

**Comment by JakeWharton** [comment]
Pushed a sample `Action Bar/Simple (Dark-Light Theme)` for it just specifying the theme in the manifest.

**Pull request merged**
