### PR TITLE
Menu resource onClick attribute is broken (refers to wrong object)

### PR DESCRIPTION
**Pull request by mernen**
`MenuInflater` attempts to bind the `onClick` handlers to itself, rather than to the given Context. This patch fixes this.

### CODE REVIEW

**Comment by mernen** [comment]
Also, perhaps it'd be a good idea to support handlers that take an `android.support.v4.view.MenuItem` (rather than `android.view.MenuItem`) as a parameter? I was quite surprised when it said my method was not found, I just assumed the library would favor its backport variants at all times over OS-provided classes.

**Comment by JakeWharton** [comment]
Good catch. I always use in-code bindings so this slipped through.

I will also change the callback to use the support version of `MenuItem`.

Thanks!

**Comment by mernen** [comment]
I wanted to give them a spin, but I'm a bit underwhelmed. At the moment they are limited to Context/Activity methods, and sometimes (quite often, actually) it makes much more sense to handle actions in their originating Fragment.

**Comment by JakeWharton** [comment]
Merged to `dev`. Release soon.

**Pull request closed without merging**
