### PR TITLE
 Add a generic logger interface that mimics android.util.Log so another ...

### PR DESCRIPTION
**Pull request by robUx4**
I am working on a generic API for android libraries so it's easier for the lib user to redirect the logs to something else. It's transparent if you don't call LogManager.setLogger()

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why not just use a normal [`Logger`](https://developer.android.com/reference/java/util/logging/Logger.html)?

**Comment by robUx4** [comment]
This is a heavy class to use. An interface that mimics android.util.Log is a lot easier to implement and calls are easy to replace without making any mistakes.

**Comment by JakeWharton** [comment]
I don't see the value-add here. ABS's logging is compiled out due to the `static final` constant that prefixes each call to `Log`. If anything we should just switch it to `BuildConfig.DEBUG` now that it's provided by the tooling to allow enabling and disabling based on your compilation mode rather than flipping a `boolean` in each file.

**Comment by robUx4** [comment]
Not sure having the static boolean centralized will remove the code like it does now (pretty sure it doesn't). 
If you haven't seen my G+ post, the idea is to be able to redirect the logs of any libs to your own logger. The java Logger could fit but is too heavy. A simple interface that just replaces the Android Log class is easy for everyone. 
The question of whether a lib needs some logs known to the upper level is another question that varies depending on each lib.

**Comment by JakeWharton** [comment]
The `BuildConfig` boolean is still a `static final` constant and thus causes `javac` to just throw away code (you can verify with `javap`).

**Comment by iNoles** [comment]
I uses this for my applications, http://code.google.com/p/iosched/source/browse/android/src/com/google/android/apps/iosched/util/LogUtils.java

**Pull request closed without merging**
