### PR TITLE
Additional protections for #557.

### PR DESCRIPTION
**Pull request by Digipom**
This is in conjunction with the pull request for #415

### CODE REVIEW

**Comment by JakeWharton** [comment]
When would this ever happen?

**Comment by iNoles** [comment]
http://developer.android.com/reference/android/database/Observable.html#registerObserver%28T%29 If observed registered more than once, it will throws IllegalStateException. There is unregisterObserver for it.

**Comment by JakeWharton** [comment]
I'm aware of that. But when would that ever happen?

**Comment by Digipom** [comment]
I think I saw market reports for this, though I added this in a long time ago so I have no idea how often it happens. On the previous pull request, another commentator was asking when it would be integrated as they seem to have seen the same exceptions in the market.

**Comment by JakeWharton** [comment]
Works for me!

**Comment by JakeWharton** [comment]
Thanks for making these against `dev`, too. Merging manually gets annoying. I **promise** a release is coming soon.

**Comment by Digipom** [comment]
Thanks for all of the hard work, Action Bar Sherlock has been a life saver!

**Pull request merged**
